baseurl = "/"
languageCode = "en-us"
title = "Juan Carlos Hinojosa Peredo"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"
    doc ="/documents/:slug"

[[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Sobre mi.."
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Documents"
    url = "/documents/"
    weight = 3
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 4


[params]
    description = "Sitio personal"
    footer = "&copy; [Yihui Xie](https://yihui.name) 2017 | [Github](https://github.com/yihui) | [Twitter](https://twitter.com/xieyihui)"

  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"
